stages:
  - build
  - test

image:
  name: "maven:3.6.3-openjdk-11"

build:
  stage: build
  tags:
    - compcs140
  script:
    - cd WeatherApp/
    - mvn compile

test:
  stage: test
  tags:
    - compcs140
  script:
    - cd WeatherApp/
    - mvn test
